services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nest_network

  adminer:
    image: adminer
    container_name: my_adminer
    ports:
      - '8080:8080'
    networks:
      - nest_network

volumes:
  mysql_data:

networks:
  nest_network:
    driver: bridge
